const iconMap = {
    customerHelpPoints: 'MdHelp',
    informationAvailableFromStaff: 'MdHelp',
    departureScreens:'MdHelp' ,
    arrivalScreens: 'MdHelp',
    announcements: 'MdAnnouncement',
    ticketOffice: 'FaTicket',
    ticketMachine: 'FaTicket',
    customerService: 'MdHelp',
    leftLuggage: 'MdLuggage',
    lostProperty: 'MdLuggage',
    telephones: 'FaPhone',
    atmMachine: 'RiMoneyPoundCircleFill',
    babyChange: 'MdBabyChangingStation',
    bureauDeChange: 'RiMoneyPoundCircleFill',
    firstClassLounge: 'MdEventSeat',
    shops: 'FaShoppingBag',
    showers: 'FaShower',
    stationBuffet: 'MdFastfood',
    toilets: 'FaRestroom',
    trolleys: 'PiTrolleySuitcaseFill',
    waitingRoom: 'MdOutlineMeetingRoom',
    wifi: 'FaWifi',
    staffHelpAvailable: 'MdHelp',
    inductionLoop: 'MdHearingDisabled',
    accessibleTicketMachines: 'FaAccessibleIcon',
    rampForTrainAccess: 'FaAccessibleIcon',
    accessibleTaxis: 'FaAccessibleIcon',
    accessiblePublicTelephones: 'FaAccessibleIcon',
    nationalKeyToilets: 'FaAccessibleIcon',
    stepFreeAccess: 'FaAccessibleIcon',
    ticketGates: 'FaAccessibleIcon',
    impairedMobilitySetDown: 'FaAccessibleIcon',
    wheelchairsAvailable: 'FaWheelchair',
    airport: 'FaPlaneDeparture',
    carPark: 'FaCar',
    cycleStorage: 'FaBicycle',
    metroServices: 'FaSubway',
    onwardTravel: 'MdDepartureBoard',
    taxiRank: 'FaTaxi',
};

export default iconMap;