interface IconMap {
    customerHelpPoints: string;
    informationAvailableFromStaff: string;
    departureScreens:string ;
    arrivalScreens: string;
    announcements: string;
    ticketOffice: string;
    ticketMachine: string;
    customerService: string;
    leftLuggage: string;
    lostProperty: string;
    telephones: string;
    atmMachine: string;
    babyChange: string;
    bureauDeChange: string;
    firstClassLounge: string;
    shops: string;
    showers: string;
    stationBuffet: string;
    toilets: string;
    trolleys: string;
    waitingRoom: string;
    wifi: string;
    staffHelpAvailable: string;
    inductionLoop: string;
    accessibleTicketMachines: string;
    rampForTrainAccess: string;
    accessibleTaxis: string;
    accessiblePublicTelephones: string;
    nationalKeyToilets: string;
    stepFreeAccess: string;
    ticketGates: string;
    impairedMobilitySetDown: string;
    wheelchairsAvailable: string;
    airport: string;
    carPark: string;
    cycleStorage: string;
    metroServices: string;
    onwardTravel: string;
    taxiRank: string;
}

export default IconMap;